# Generated by Django 4.0 on 2023-05-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dni',
            field=models.BigIntegerField(default=0),
        ),
    ]
